name: 2.2.simple_workflow.yaml
on:
  push:
    #branches:
      #.main
jobs:
  runs-on: ubuntu-latest
  steps:
  -name: Say Hello
  run: echo "Ceci est le premier job.!"
jobs:
  runs-on: ubuntu-latest
  steps:
  -name: Say Hello
  run: echo "Ceci est mon second job.!"
jobs:
  runs-on: ubuntu-latest
  steps:
  -name: Say Hello
  run: echo "Ceci est mon troisieme job.!"